import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { withClient } from '../config/client';

dotenv.config();

const ROLES = [
  { seedKey: 'INVESTOR_A_SEED', addressKey: 'INVESTOR_A_ADDRESS', label: 'InvestorA' },
  { seedKey: 'INVESTOR_B_SEED', addressKey: 'INVESTOR_B_ADDRESS', label: 'InvestorB' },
  { seedKey: 'BORROWER_SEED', addressKey: 'BORROWER_ADDRESS', label: 'Borrower' },
  { seedKey: 'BROKER_SEED', addressKey: 'BROKER_ADDRESS', label: 'Broker' },
  { seedKey: 'UNCREDENTIALED_SEED', addressKey: 'UNCREDENTIALED_ADDRESS', label: 'Uncredentialed' },
] as const;

async function main(): Promise<void> {
  console.log('=== A1: Account Setup — XRPL Devnet Faucet ===\n');

  const funded: Array<{ label: string; address: string; seed: string; balance: string }> = [];

  await withClient(async (client) => {
    for (const role of ROLES) {
      process.stdout.write(`Funding ${role.label}...`);
      const { wallet, balance } = await client.fundWallet();
      funded.push({ label: role.label, address: wallet.classicAddress, seed: wallet.seed!, balance: String(balance) });
      console.log(` OK — ${wallet.classicAddress} (${balance} XRP)`);
    }
  });

  const envPath = path.resolve(__dirname, '../.env');

  // Read existing .env so we preserve any SMOKE_ / VAULT_ / LOAN_ keys
  let existing = '';
  try { existing = fs.readFileSync(envPath, 'utf-8'); } catch { /* first run */ }

  const accountKeys = new Set<string>(ROLES.flatMap((r) => [r.seedKey, r.addressKey]));
  const lines = existing ? existing.split('\n') : [];
  const kept = lines.filter((l) => {
    const [k] = l.split('=');
    return k && !accountKeys.has(k.trim());
  });

  const accountBlock = [
    '# XRPL public Devnet — account seeds + classic addresses',
    '# Generated by scripts/01_setup_accounts.ts',
    '# Addresses are public (explorer); seeds are secret — never commit .env',
    ...funded.flatMap((f, i) => [
      `${ROLES[i].seedKey}=${f.seed}`,
      `${ROLES[i].addressKey}=${f.address}`,
    ]),
    '',
    '# Network',
    'XRPL_WSS=wss://s.devnet.rippletest.net:51233/',
    'XRPL_RPC=https://s.devnet.rippletest.net:51234/',
  ];

  const filtered = kept.filter(
    (l) =>
      !l.startsWith('XRPL_WSS=') &&
      !l.startsWith('XRPL_RPC=') &&
      !l.startsWith('# Network') &&
      !l.startsWith('# XRPL public') &&
      !l.startsWith('# Generated by') &&
      !l.startsWith('# Addresses are'),
  );

  const content = [...accountBlock, ...filtered.filter(Boolean)].join('\n') + '\n';
  fs.writeFileSync(envPath, content);

  console.log('\n=== Summary ===');
  for (const f of funded) {
    console.log(`${f.label.padEnd(16)} ${f.address}  (${f.balance} XRP)`);
  }
  console.log(`\nSeeds + addresses written to .env`);
  console.log('\nNext step: npm run smoke:a2');
}

main().catch((err: Error) => {
  console.error('\nA1 FAILED:', err.message);
  process.exit(1);
});
