import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { withClient } from '../config/client';

dotenv.config();

const ROLES = [
  { key: 'INVESTOR_A_SEED', label: 'InvestorA' },
  { key: 'INVESTOR_B_SEED', label: 'InvestorB' },
  { key: 'BORROWER_SEED',   label: 'Borrower'  },
  { key: 'BROKER_SEED',     label: 'Broker'    },
  { key: 'UNCREDENTIALED_SEED', label: 'Uncredentialed' },
] as const;

async function main(): Promise<void> {
  console.log('=== A1: Account Setup — XRPL Devnet Faucet ===\n');

  const funded: Array<{ label: string; address: string; seed: string; balance: string }> = [];

  await withClient(async (client) => {
    for (const role of ROLES) {
      process.stdout.write(`Funding ${role.label}...`);
      const { wallet, balance } = await client.fundWallet();
      funded.push({ label: role.label, address: wallet.classicAddress, seed: wallet.seed!, balance: String(balance) });
      console.log(` OK — ${wallet.classicAddress} (${balance} XRP)`);
    }
  });

  const envPath = path.resolve(__dirname, '../.env');

  // Read existing .env so we preserve any SMOKE_ or other keys
  let existing = '';
  try { existing = fs.readFileSync(envPath, 'utf-8'); } catch { /* first run */ }

  // Overwrite seed lines; preserve other keys
  const lines = existing ? existing.split('\n') : [];
  const seedKeys = new Set(ROLES.map((r) => r.key));
  const kept = lines.filter((l) => {
    const [k] = l.split('=');
    return k && !seedKeys.has(k.trim());
  });

  const seedBlock = [
    '# XRPL public Devnet — account seeds',
    '# Generated by scripts/01_setup_accounts.ts',
    ...funded.map((f, i) => `${ROLES[i].key}=${f.seed}`),
    '',
    '# Network',
    'XRPL_WSS=wss://s.devnet.rippletest.net:51233/',
    'XRPL_RPC=https://s.devnet.rippletest.net:51234/',
  ];

  // Remove old network block from kept lines to avoid duplication
  const filtered = kept.filter((l) => !l.startsWith('XRPL_WSS=') && !l.startsWith('XRPL_RPC=') && !l.startsWith('# Network') && !l.startsWith('# XRPL public') && !l.startsWith('# Generated by'));

  const content = [...seedBlock, ...filtered.filter(Boolean)].join('\n') + '\n';
  fs.writeFileSync(envPath, content);

  console.log('\n=== Summary ===');
  for (const f of funded) {
    console.log(`${f.label.padEnd(16)} ${f.address}  (${f.balance} XRP)`);
  }
  console.log(`\nSeeds written to .env`);
  console.log('\nNext step: npm run smoke:a2');
}

main().catch((err: Error) => {
  console.error('\nA1 FAILED:', err.message);
  process.exit(1);
});
